import streamlit as st
import pandas as pd
import numpy as np
import glob
import os
import time
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# =====================================================================
# PAGE CONFIG & AUTO REFRESH
# =====================================================================
st.set_page_config(
    page_title="EnergyLens | HVAC Loss & Efficiency Monitor",
    layout="wide",
    page_icon="👁️"
)

# Fixed CSS for visibility and Branding
st.markdown("""
    <style>
    /* Metric Card Styling */
    div[data-testid="stMetric"] {
        background-color: rgba(16, 185, 129, 0.05); /* EnergyLens Emerald Tint */
        border: 1px solid rgba(16, 185, 129, 0.2);
        padding: 15px 20px;
        border-radius: 12px;
        color: inherit;
    }
    
    /* Ensure metric labels and values are sharp */
    div[data-testid="stMetricLabel"] > div {
        font-size: 14px !important;
        font-weight: 600 !important;
        color: inherit !important;
        opacity: 0.8;
    }
    
    div[data-testid="stMetricValue"] > div {
        font-size: 28px !important;
        font-weight: 700 !important;
        color: #10b981 !important; /* EnergyLens Emerald */
    }

    h1, h2, h3 {
        font-weight: 800 !important;
    }
    
    /* Branding Header */
    .brand-text {
        color: #10b981;
        font-weight: 900;
        letter-spacing: -0.05em;
    }
    </style>
    """, unsafe_allow_html=True)

if "last_refresh" not in st.session_state:
    st.session_state.last_refresh = time.time()

if (time.time() - st.session_state.last_refresh) > 15 * 60:
    st.session_state.last_refresh = time.time()
    st.rerun()

# =====================================================================
# ALERT STATE TRACKING
# =====================================================================
if "ghost_alert_active" not in st.session_state:
    st.session_state.ghost_alert_active = False
if "cooling_alert_active" not in st.session_state:
    st.session_state.cooling_alert_active = False

# =====================================================================
# EMAIL ALERT SYSTEM
# =====================================================================
def send_gmail_alert(subject, html_body):
    try:
        sender_email = st.secrets["gmail"]["user"]
        sender_password = st.secrets["gmail"]["password"]
        receiver_email = st.secrets["gmail"]["receiver"]

        msg = MIMEMultipart()
        msg["From"] = f"EnergyLens Intelligence <{sender_email}>"
        msg["To"] = receiver_email
        msg["Subject"] = f"EnergyLens Alert: {subject}"
        msg.attach(MIMEText(html_body, "html"))

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
    except Exception as e:
        st.sidebar.error(f"Email alert failed: {e}")

# =====================================================================
# EMAIL TEMPLATES
# =====================================================================
def ghost_running_email(hours, cost, carbon):
    return f"""
    <div style="font-family: sans-serif; border-left: 4px solid #10b981; padding-left: 20px;">
        <h2 style="color: #0f172a;">EnergyLens: HVAC Operating Outside Occupancy</h2>
        <p><b>Unnecessary Runtime:</b> {hours} hours</p>
        <p><b>Estimated Cost Impact:</b> ₹{int(cost):,}</p>
        <p><b>CO₂ Impact:</b> {int(carbon)} kg</p>
        <p style="font-size: 12px; color: #64748b;">Generated by EnergyLens Energy Wastage Intelligence</p>
    </div>
    """

def overcooling_email(loss, avg_dt):
    return f"""
    <div style="font-family: sans-serif; border-left: 4px solid #10b981; padding-left: 20px;">
        <h2 style="color: #0f172a;">EnergyLens: Excess Cooling Detected</h2>
        <p><b>Estimated Cooling Loss:</b> ₹{int(loss):,}</p>
        <p><b>Average Temperature Deviation:</b> {avg_dt:.1f}°C below setpoint</p>
        <p style="font-size: 12px; color: #64748b;">Generated by EnergyLens Energy Wastage Intelligence</p>
    </div>
    """

# =====================================================================
# DATA HELPERS
# =====================================================================
@st.cache_data(ttl=60)
def load_latest_csv(folder):
    try:
        files = glob.glob(os.path.join(folder, "*.csv"))
        if not files:
            return None, None
        latest = max(files, key=os.path.getmtime)
        return pd.read_csv(latest), latest
    except:
        return None, None

def calculate_carbon(kwh):
    return kwh * 0.71

# =====================================================================
# EXPLAINABILITY
# =====================================================================
def explainability_manager(title, why, impact):
    with st.expander("🔍 Why this matters (EnergyLens Insight)"):
        st.markdown(f"### {title}")
        st.write(why)
        st.info(impact)

def explainability_operator(rules, signals, checks):
    with st.expander("🛠️ How this was detected (EnergyLens Intelligence Layer)"):
        st.markdown("**Detection Rules Applied**")
        for r in rules:
            st.write(f"• {r}")
        st.markdown("**Signals Used**")
        for s in signals:
            st.write(f"• {s}")
        st.markdown("**Actionable Next Steps**")
        for c in checks:
            st.write(f"• {c}")

# =====================================================================
# SIDEBAR
# =====================================================================
st.sidebar.markdown("### <span class='brand-text'>EnergyLens</span>", unsafe_allow_html=True)
st.sidebar.caption("Operational Configuration")
BASE_PATH = st.sidebar.text_input("Live Data Folder Path", value="scenario_data/live")
cost_rate = st.sidebar.number_input("Electricity Cost Rate (₹/kWh)", value=12.0)
cooling_factor = st.sidebar.number_input("Cooling Penalty Cost (₹ / °C / hour)", value=150.0)
off_start = st.sidebar.slider("Non-Occupancy Start Hour", 0, 23, 22)
off_end = st.sidebar.slider("Non-Occupancy End Hour", 0, 23, 6)
enable_email = st.sidebar.checkbox("Enable EnergyLens Email Alerts", value=False)

# =====================================================================
# MAIN DASHBOARD
# =====================================================================
st.markdown("<h1><span class='brand-text'>EnergyLens</span> HVAC Monitor</h1>", unsafe_allow_html=True)
st.caption("Energy Wastage Intelligence for Smart Buildings")

scenario = st.selectbox(
    "Select Intelligence Scenario",
    [
        "🚨 HVAC Running Outside Occupancy Hours",
        "❄️ Excess Cooling / Control Inefficiency"
    ]
)

view_mode = st.radio(
    "Viewer Perspective",
    ["👔 Facilities Manager", "🎛️ BMS Operator"],
    horizontal=True
)

# =====================================================================
# DATA LOAD
# =====================================================================
p_df, _ = load_latest_csv(os.path.join(BASE_PATH, "power"))
s_df, _ = load_latest_csv(os.path.join(BASE_PATH, "status"))
t_df, _ = load_latest_csv(os.path.join(BASE_PATH, "temp"))
v_df, _ = load_latest_csv(os.path.join(BASE_PATH, "valve"))

if any(x is None for x in [p_df, s_df, t_df, v_df]):
    st.error("EnergyLens could not detect live data streams. Please verify folder mapping.")
    st.stop()

st.divider()

# =====================================================================
# SCENARIO 1 — OUTSIDE OCCUPANCY
# =====================================================================
if "Outside Occupancy" in scenario:
    p_df["T_Stamp"] = pd.to_datetime(p_df["T_Stamp"])
    p_df = p_df.set_index("T_Stamp").resample("1h").mean()
    s_df["Log_Time"] = pd.to_datetime(s_df["Log_Time"])
    s_df = s_df.set_index("Log_Time").resample("1h").ffill()

    df = pd.concat([p_df, s_df], axis=1).dropna()
    df.columns = ["Power_kW", "Unit_Status"]

    df["Actual_Status"] = np.where(df["Unit_Status"] > 0.5, "ON", "OFF")
    df["Hour"] = df.index.hour

    if off_start > off_end:
        df["Scheduled_Status"] = df["Hour"].apply(lambda h: "OFF" if (h >= off_start or h < off_end) else "ON")
    else:
        df["Scheduled_Status"] = df["Hour"].apply(lambda h: "OFF" if (off_start <= h < off_end) else "ON")

    df["Energy_Cost"] = df["Power_kW"] * cost_rate
    waste_df = df[(df["Actual_Status"] == "ON") & (df["Scheduled_Status"] == "OFF")]

    condition_active = len(waste_df) >= 2
    if enable_email and condition_active and not st.session_state.ghost_alert_active:
        send_gmail_alert(
            "HVAC Operating Outside Occupancy",
            ghost_running_email(
                len(waste_df),
                waste_df["Energy_Cost"].sum(),
                calculate_carbon(waste_df["Power_kW"].sum())
            )
        )
        st.session_state.ghost_alert_active = True
    if not condition_active:
        st.session_state.ghost_alert_active = False

    if "Manager" in view_mode:
        st.info("EnergyLens detected significant energy leakage during scheduled building shutdown.")
        st.metric("Estimated Cost Wastage", f"₹{int(waste_df['Energy_Cost'].sum()):,}")

        cols = st.columns(3)
        cols[0].metric("Projected Monthly Leakage", f"₹{int(waste_df['Energy_Cost'].sum()*30):,}")
        cols[1].metric("Ghost Runtime", f"{len(waste_df)} hrs")
        cols[2].metric("Carbon Footprint", f"{int(calculate_carbon(waste_df['Power_kW'].sum()))} kg")

        st.bar_chart(df["Energy_Cost"])
        explainability_manager("Ghost Energy Consumption", 
                               "The HVAC system remains operational despite zero occupancy logic being active.", 
                               "This leakage indicates a breakdown in scheduling or manual overrides that were never reset.")

    else:
        st.warning("Detection: Active Load during Off-Hours")
        st.markdown("### ✅ EnergyLens Recovery Steps")
        st.markdown("1. Cross-reference BMS global schedule\n2. Audit local overrides on AHU-04 controller\n3. Verify night-purge logic triggers")
        st.line_chart(df["Power_kW"])
        st.dataframe(df[["Power_kW", "Actual_Status", "Scheduled_Status"]], use_container_width=True)
        explainability_operator(["Unit status = ON", "Scheduled status = OFF", "Consumption > Idle Load"], 
                               ["Main Power Feed", "BMS Status Register", "Occupancy Clock"], 
                               ["Check local H-O-A switches", "Verify BACnet write priority", "Sync BMS clock"])

# =====================================================================
# SCENARIO 2 — EXCESS COOLING
# =====================================================================
else:
    t_df["Timestamp"] = pd.to_datetime(t_df["Timestamp"])
    t_df = t_df.set_index("Timestamp").resample("15min").interpolate()
    v_df["Log_Time"] = pd.to_datetime(v_df["Log_Time"])
    v_df = v_df.set_index("Log_Time").resample("15min").ffill()

    df = pd.concat([t_df, v_df], axis=1).dropna()
    df.columns = ["Room_Temp", "Setpoint", "Valve_Position"]

    df["Fault"] = (df["Room_Temp"] < df["Setpoint"] - 1) & (df["Valve_Position"] > 80)
    df["Delta_T"] = (df["Setpoint"] - df["Room_Temp"]).clip(0)
    df["Cooling_Loss"] = df["Delta_T"] * cooling_factor * df["Fault"]

    condition_active = df["Cooling_Loss"].sum() >= 500
    if enable_email and condition_active and not st.session_state.cooling_alert_active:
        send_gmail_alert(
            "Excess Cooling / Inefficiency",
            overcooling_email(
                df["Cooling_Loss"].sum(),
                df[df["Fault"]]["Delta_T"].mean() if df["Fault"].any() else 0
            )
        )
        st.session_state.cooling_alert_active = True
    if not condition_active:
        st.session_state.cooling_alert_active = False

    if "Manager" in view_mode:
        st.info("EnergyLens identifies control loop instability resulting in over-cooling and energy waste.")
        st.metric("Calculated Efficiency Loss", f"₹{int(df['Cooling_Loss'].sum()):,}")

        cols = st.columns(3)
        cols[0].metric("Monthly Risk Exposure", f"₹{int(df['Cooling_Loss'].sum()*30):,}")
        cols[1].metric("Avg Comfort Deviation", f"{df[df['Fault']]['Delta_T'].mean():.1f}°C" if df["Fault"].any() else "0.0°C")
        cols[2].metric("CO₂ Impact (Wastage)", f"{int(calculate_carbon(df['Cooling_Loss'].sum()/15))} kg")

        st.line_chart(df[["Room_Temp", "Setpoint"]])
        explainability_manager("Over-Cooling Inefficiency", 
                               "The system is driving cooling valves full-open even when the temperature is below setpoint.", 
                               "This typically indicates a 'hunting' PID loop or a physically stuck cooling valve actuator.")

    else:
        st.warning("Detection: Control Loop Conflict")
        st.markdown("### ✅ EnergyLens Recovery Steps")
        st.markdown("1. Inspect Actuator feedback vs Command\n2. Re-tune PID Cooling Loop parameters\n3. Check for sensor drift or placement issues")
        st.line_chart(df[["Valve_Position", "Room_Temp"]])
        st.dataframe(df[["Room_Temp", "Setpoint", "Valve_Position", "Fault"]], use_container_width=True)
        explainability_operator(["Temp < Setpoint - 1.0", "Valve Command > 80%", "Non-responsive feedback"], 
                               ["Zone Temp Sensor", "BMS Setpoint", "Valve Actuator Command"], 
                               ["Physical valve inspection", "PID Tuning", "Sensor calibration check"])

# =====================================================================
# EXPORT & FOOTER
# =====================================================================
st.divider()
with st.expander("📥 Export Evidence for Reporting"):
    st.dataframe(processed_df if 'processed_df' in locals() else df, use_container_width=True)
    st.download_button(
        "Download EnergyLens Audit CSV",
        (processed_df if 'processed_df' in locals() else df).to_csv().encode("utf-8"),
        file_name="energylens_audit_report.csv",
        mime="text/csv"
    )

st.markdown(
    f"<p style='text-align: center; color: #64748b; font-size: 12px; margin-top: 50px;'>"
    f"© 2026 <b>EnergyLens</b> Intelligence Layer · BMS Agnostic · Read-Only <br>"
    f"Last Intelligence Sync: {time.strftime('%H:%M:%S')}"
    f"</p>", 
    unsafe_allow_html=True
)