import streamlit as st
import pandas as pd
import numpy as np
import glob
import os
import time
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# =====================================================================
# PAGE CONFIG & AUTO REFRESH
# =====================================================================
st.set_page_config(
    page_title="EnergyLens | HVAC Loss & Efficiency Monitor",
    layout="wide",
    page_icon="👁️"
)

# =============================
# CSS (McKinsey Style)
# =============================
st.markdown("""
<style>
/* General */
.block-container {
    padding-top: 2rem;
}

/* Metric Card */
div[data-testid="stMetric"] {
    background-color: rgba(16, 185, 129, 0.05);
    border: 1px solid rgba(16, 185, 129, 0.2);
    padding: 15px 20px;
    border-radius: 12px;
}

/* Metric Label */
div[data-testid="stMetricLabel"] {
    font-size: 14px !important;
    font-weight: 600 !important;
    opacity: 0.8;
}

/* Metric Value */
div[data-testid="stMetricValue"] {
    font-size: 36px !important;
    font-weight: 700 !important;
    color: #10b981 !important;
}

/* HERO KPI (Annual Leakage) */
.hero-kpi {
    background: linear-gradient(135deg, rgba(239,68,68,0.1), rgba(239,68,68,0.05));
    border: 1px solid rgba(239,68,68,0.3);
    padding: 30px;
    border-radius: 16px;
    margin-top: 15px;
}

.hero-label {
    font-size: 16px;
    font-weight: 600;
    opacity: 0.8;
}

.hero-value {
    font-size: 64px;
    font-weight: 900;
    color: #ef4444;
}

.hero-sub {
    font-size: 14px;
    opacity: 0.7;
}

/* Title */
h1 {
    font-weight: 800;
}

/* Alert Banner */
.alert-banner {
    background-color: #fef2f2;
    border: 1px solid #fee2e2;
    color: #991b1b;
    padding: 1rem;
    border-radius: 0.5rem;
    margin-bottom: 2rem;
    display: flex;
    align-items: center;
    gap: 10px;
}

/* Strategic Differentiation Styling */
.diff-box {
    padding: 25px;
    border-radius: 12px;
    margin-bottom: 15px;
    min-height: 450px; /* Ensures both boxes are the same height */
    display: flex;
    flex-direction: column;
}
.fdd-box { 
    background-color: #f8fafc; 
    border: 1px solid #e2e8f0; 
    border-left: 6px solid #64748b;
}
.el-box { 
    background-color: #f0fdf4; 
    border: 1px solid #bbf7d0; 
    border-left: 6px solid #22c55e;
}
</style>
""", unsafe_allow_html=True)


if "last_refresh" not in st.session_state:
    st.session_state.last_refresh = time.time()

if (time.time() - st.session_state.last_refresh) > 15 * 60:
    st.session_state.last_refresh = time.time()
    st.rerun()

# =====================================================================
# ALERT STATE TRACKING
# =====================================================================
if "ghost_alert_active" not in st.session_state:
    st.session_state.ghost_alert_active = False
if "cooling_alert_active" not in st.session_state:
    st.session_state.cooling_alert_active = False

# =====================================================================
# EMAIL ALERT SYSTEM
# =====================================================================
def send_gmail_alert(subject, html_body):
    try:
        sender_email = st.secrets["gmail"]["user"]
        sender_password = st.secrets["gmail"]["password"]
        receiver_email = st.secrets["gmail"]["receiver"]

        msg = MIMEMultipart()
        msg["From"] = f"EnergyLens Intelligence <{sender_email}>"
        msg["To"] = receiver_email
        msg["Subject"] = f"EnergyLens Alert: {subject}"
        msg.attach(MIMEText(html_body, "html"))

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
    except Exception as e:
        st.sidebar.error(f"Email alert failed: {e}")

# =====================================================================
# EMAIL TEMPLATES
# =====================================================================
def ghost_running_email(hours, cost, carbon):
    return f"""
    <div style="font-family: sans-serif; border-left: 4px solid #10b981; padding-left: 20px;">
        <h2 style="color: #0f172a;">EnergyLens: HVAC Schedule Drift Detected</h2>
        <p><b>Unnecessary Runtime:</b> {hours} hours</p>
        <p><b>Estimated Cost Impact:</b> ${int(cost):,}</p>
        <p><b>CO₂ Impact:</b> {int(carbon)} kg</p>
        <p style="font-size: 12px; color: #64748b;">Generated by EnergyLens Energy Wastage Intelligence</p>
    </div>
    """

def overcooling_email(loss, avg_dt):
    return f"""
    <div style="font-family: sans-serif; border-left: 4px solid #10b981; padding-left: 20px;">
        <h2 style="color: #0f172a;">EnergyLens: Sub-Setpoint Hunting Detected</h2>
        <p><b>Estimated Cooling Loss:</b> ${int(loss):,}</p>
        <p><b>Average Temperature Deviation:</b> {avg_dt:.1f}°C below setpoint</p>
        <p style="font-size: 12px; color: #64748b;">Generated by EnergyLens Energy Wastage Intelligence</p>
    </div>
    """

# =====================================================================
# DATA HELPERS
# =====================================================================
@st.cache_data(ttl=60)
def load_latest_csv(folder):
    try:
        files = glob.glob(os.path.join(folder, "*.csv"))
        if not files:
            return None, None
        latest = max(files, key=os.path.getmtime)
        return pd.read_csv(latest), latest
    except:
        return None, None

def calculate_carbon(kwh):
    return kwh * 0.71

# =====================================================================
# EXPLAINABILITY
# =====================================================================
def explainability_manager(title, why, impact):
    with st.expander("🔍 Why this matters (EnergyLens Insight)"):
        st.markdown(f"### {title}")
        st.write(why)
        st.info(impact)

def explainability_operator(rules, signals, checks):
    with st.expander("🛠️ How this was detected (EnergyLens Intelligence Layer)"):
        st.markdown("**Detection Rules Applied**")
        for r in rules:
            st.write(f"• {r}")
        st.markdown("**Signals Used**")
        for s in signals:
            st.write(f"• {s}")
        st.markdown("**Actionable Next Steps**")
        for c in checks:
            st.checkbox(c, key=f"check_{c[:10]}")

# =====================================================================
# SIDEBAR
# =====================================================================
st.sidebar.markdown("### <span class='brand-text'>EnergyLens</span>", unsafe_allow_html=True)
st.sidebar.caption("Operational Configuration")
BASE_PATH = st.sidebar.text_input("Live Data Folder Path", value="scenario_data/live")
cost_rate = st.sidebar.number_input("Electricity Cost Rate ($/kWh)", value=0.25)
cooling_factor = st.sidebar.number_input("Cooling Penalty Cost ($ / °C / hour)", value=10.0)
off_start = st.sidebar.slider("Non-Occupancy Start Hour", 0, 23, 22)
off_end = st.sidebar.slider("Non-Occupancy End Hour", 0, 23, 6)
enable_email = st.sidebar.checkbox("Enable EnergyLens Email Alerts", value=False)

# =====================================================================
# MAIN DASHBOARD
# =====================================================================
st.markdown("<h1><span class='brand-text'>EnergyLens</span> HVAC Monitor</h1>", unsafe_allow_html=True)
st.caption("Energy Wastage Intelligence for Smart Buildings")

# --- NAVIGATION TABS ---
# This addresses the committee question: "Is this just another FDD tool?"
tabs = st.tabs(["📊 Live Intelligence", "🛡️ Strategic Differentiation (EnergyLens vs FDD)"])

with tabs[0]:
    # =====================================================================
    # STANDARDIZED 12 CORE WASTE CATEGORIES
    # =====================================================================
    scenario = st.selectbox(
        "Select Intelligence Scenario",
        [
            "🚨 Schedule Drift (Operating Outside Occupancy)",
            "❄️ Excessive Cooling (Sub-Setpoint Hunting)",
            "🔄 Simultaneous Heating & Cooling (Mechanical Conflict)",
            "👥 Occupancy-Conditioning Mismatch (Zombie Zones)",
            "🌬️ Static Pressure Oversupply (Fan Affinity Loss)",
            "📈 Short Cycling (Rapid Compressor Sequencing)",
            "📉 Economizer Failure (Mechanical vs Natural Cooling)",
            "🌡️ Sensor Drift & Calibration Error",
            "💧 Humidification/Dehumidification Conflict",
            "⚙️ Valve/Damper Actuator Staging Inefficiency",
            "🛠️ Manual Override Persistence (Permanent Temporary Fixes)",
            "📉 Pump Delta-P Inefficiency (Low Delta-T Syndrome)"
        ]
    )

    view_mode = st.radio(
        "Viewer Perspective",
        ["👔 Facilities Manager", "🎛️ BMS Operator"],
        horizontal=True
    )

    # =====================================================================
    # DATA LOAD
    # =====================================================================
    p_df, _ = load_latest_csv(os.path.join(BASE_PATH, "power"))
    s_df, _ = load_latest_csv(os.path.join(BASE_PATH, "status"))
    t_df, _ = load_latest_csv(os.path.join(BASE_PATH, "temp"))
    v_df, _ = load_latest_csv(os.path.join(BASE_PATH, "valve"))

    if any(x is None for x in [p_df, s_df, t_df, v_df]):
        st.error("EnergyLens could not detect live data streams. Please verify folder mapping.")
        st.stop()

    st.divider()

    # =====================================================================
    # SCENARIO 1 — SCHEDULE DRIFT
    # =====================================================================
    if "Schedule Drift" in scenario:
        p_df["T_Stamp"] = pd.to_datetime(p_df["T_Stamp"])
        p_df = p_df.set_index("T_Stamp").resample("1h").mean()
        s_df["Log_Time"] = pd.to_datetime(s_df["Log_Time"])
        s_df = s_df.set_index("Log_Time").resample("1h").ffill()

        df = pd.concat([p_df, s_df], axis=1, sort=False).dropna()
        df.columns = ["Power_kW", "Unit_Status"]

        df["Actual_Status"] = np.where(df["Unit_Status"] > 0.5, "ON", "OFF")
        df["Hour"] = df.index.hour

        if off_start > off_end:
            df["Scheduled_Status"] = df["Hour"].apply(lambda h: "OFF" if (h >= off_start or h < off_end) else "ON")
        else:
            df["Scheduled_Status"] = df["Hour"].apply(lambda h: "OFF" if (off_start <= h < off_end) else "ON")

        df["Energy_Cost"] = df["Power_kW"] * cost_rate
        
        df["Is_Waste"] = (df["Actual_Status"] == "ON") & (df["Scheduled_Status"] == "OFF")
        waste_df = df[df["Is_Waste"]]

        energy_kwh = waste_df["Power_kW"].sum()
        daily_cost = round(waste_df['Energy_Cost'].sum(), 0)
        monthly_cost = daily_cost * 30 
        annual_cost = monthly_cost * 12 

        condition_active = len(waste_df) >= 2
        
        if condition_active:
            st.markdown("""<div class="alert-banner">🚨 <b>ACTIVE WASTAGE DETECTED:</b> System operating in Schedule Drift (AHU-04) during non-occupancy hours.</div>""", unsafe_allow_html=True)

        if enable_email and condition_active and not st.session_state.ghost_alert_active:
            send_gmail_alert("HVAC Schedule Drift Alert", ghost_running_email(len(waste_df), daily_cost, calculate_carbon(energy_kwh)))
            st.session_state.ghost_alert_active = True
        
        if not condition_active:
            st.session_state.ghost_alert_active = False

        if "Manager" in view_mode:
            st.info("EnergyLens detected significant energy leakage during scheduled building shutdown.")
            st.metric("Estimated Cost Wastage", f"${daily_cost:,.0f}")

            cols = st.columns(4)
            cols[0].metric("Projected Monthly Leakage", f"${monthly_cost:,.0f}")
            cols[1].metric("Ghost Runtime", f"{len(waste_df)} hrs")
            cols[2].metric("Energy Wasted", f"{energy_kwh:,.0f} kWh")
            cols[3].metric("Carbon Footprint", f"{int(calculate_carbon(waste_df['Power_kW'].sum()))} kg")

            st.markdown(f"""
            <div class="hero-kpi">
                <div class="hero-label">Projected Annual Leakage</div>
                <div class="hero-value">${annual_cost:,.0f}</div>
                <div class="hero-sub">Estimated annual energy wastage due to schedule drift.</div>
            </div>
            """, unsafe_allow_html=True)

            st.subheader("Hourly Energy Cost ($)")
            chart_data = df[['Energy_Cost']].copy()
            chart_data['Scheduled Energy'] = np.where(~df['Is_Waste'], df['Energy_Cost'], 0)
            chart_data['Wasted Energy'] = np.where(df['Is_Waste'], df['Energy_Cost'], 0)
            st.bar_chart(chart_data[['Scheduled Energy', 'Wasted Energy']], color=["#10b981", "#ef4444"], width='stretch')
            
            explainability_manager("Schedule Drift Inefficiency", 
                                    "The HVAC system remains operational despite zero occupancy logic being active.", 
                                    "This indicates a breakdown in scheduling or manual overrides that were never reset.")
        else:
            st.warning("Detection: Active Load during Off-Hours")
            explainability_operator(["Unit status = ON", "Scheduled status = OFF", "Consumption > Idle Load"], 
                                    ["Main Power Feed", "BMS Status Register", "Occupancy Clock"], 
                                    ["Cross-reference BMS global schedule", "Audit local overrides on AHU-04 controller", "Verify night-purge logic triggers", "Sync BMS clock"])
            st.line_chart(df["Power_kW"], width='stretch')

    # =====================================================================
    # SCENARIO 2 — EXCESSIVE COOLING
    # =====================================================================
    elif "Excessive Cooling" in scenario:
        t_df["Timestamp"] = pd.to_datetime(t_df["Timestamp"])
        t_df = t_df.set_index("Timestamp").resample("15min").interpolate()
        v_df["Log_Time"] = pd.to_datetime(v_df["Log_Time"])
        v_df = v_df.set_index("Log_Time").resample("15min").ffill()

        df = pd.concat([t_df, v_df], axis=1, sort=False).dropna()
        df.columns = ["Room_Temp", "Setpoint", "Valve_Position"]

        df["Fault"] = (df["Room_Temp"] < df["Setpoint"] - 1) & (df["Valve_Position"] > 80)
        df["Delta_T"] = (df["Setpoint"] - df["Room_Temp"]).clip(0)
        df["Power_Loss_kW"] = df["Delta_T"] * cooling_factor * df["Fault"]
        df["Energy_Loss_kWh"] = df["Power_Loss_kW"] * 0.25

        total_energy_loss = df["Energy_Loss_kWh"].sum()
        cost_loss = total_energy_loss * cost_rate
        carbon_loss = calculate_carbon(total_energy_loss)
        
        if total_energy_loss >= 500:
            st.markdown("""<div class="alert-banner">❄️ <b>CONTROL INEFFICIENCY:</b> Sub-setpoint hunting detected. Excessive energy used to overcool.</div>""", unsafe_allow_html=True)

        if "Manager" in view_mode:
            st.info("System is consuming energy while exceeding comfort requirements (Sub-Setpoint Hunting).")
            st.metric("Monthly Cost Impact", f"${cost_loss*30:,.0f}")
            cols = st.columns(3)
            cols[0].metric("Estimated Cooling Energy Loss", f"{total_energy_loss:,.0f} kWh")
            cols[1].metric("Avg Comfort Deviation", f"{df[df['Fault']]['Delta_T'].mean():.1f}°C" if df["Fault"].any() else "0.0°C")
            cols[2].metric("CO₂ Impact", f"{carbon_loss:,.0f} kg")
            st.line_chart(df[["Room_Temp", "Setpoint"]], width='stretch')
        else:
            st.warning("Detection: Control Loop Conflict")
            explainability_operator(["Temp < Setpoint - 1.0", "Valve Command > 80%", "Non-responsive feedback"], 
                                    ["Zone Temp Sensor", "BMS Setpoint", "Valve Actuator Command"], 
                                    ["Inspect Actuator feedback vs Command", "Re-tune PID Cooling Loop parameters", "Check for sensor drift", "Physical valve inspection"])
            st.line_chart(df[["Valve_Position", "Room_Temp"]], width='stretch')

    # =====================================================================
    # R&D MODULES PLACEHOLDER
    # =====================================================================
    else:
        st.info(f"### {scenario}")
        st.markdown("""
        **Intelligence Phase:** 🧪 R&D / Validation Cycle
        
        EnergyLens is currently standardizing the engineering logic for this category to ensure cross-sector compatibility (Airports, Hospitals, Malls, Universities).
        """)
        
        cols = st.columns(2)
        with cols[0]:
            st.markdown("#### 🔬 Engineering Logic")
            if "Simultaneous" in scenario:
                st.write("Detecting thermal 'warring' where AHU heating coils and terminal cooling valves are active in the same zone.")
            elif "Static Pressure" in scenario:
                st.write("Analyzing Fan VFD speeds vs Airflow requirements to identify over-pressurization (Fan Affinity Law wastage).")
            elif "Short Cycling" in scenario:
                st.write("Monitoring compressor start/stop frequency to prevent mechanical wear and energy surges.")
            elif "Economizer" in scenario:
                st.write("Validating enthalpy-based logic to ensure 100% outside air is used when ambient conditions permit.")
            elif "Occupancy-Conditioning" in scenario:
                st.write("Cross-referencing real-time occupancy signals (Wi-Fi/Swipe) against active air-change rates.")
            else:
                st.write("Analyzing sub-optimal control sequences using digital-twin engineering principles.")
                
        with cols[1]:
            st.markdown("#### 🎯 Target Metrics")
            st.write("• Energy Density (kWh/m²)")
            st.write("• Coefficient of Performance (COP) Drift")
            st.write("• Carbon Intensity Reduction")
        
        st.divider()
        st.image("https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1000", caption="EnergyLens Intelligence Roadmap Validation")

with tabs[1]:
    # =====================================================================
    # STRATEGIC DIFFERENTIATION SLIDE (FOR COMMITTEE)
    # =====================================================================
    st.subheader("Positioning: EnergyLens vs. Fault Detection & Diagnostics (FDD)")
    st.markdown("To ensure we aren't dismissed as 'just another FDD tool', we pivot from *maintenance* to *operational intent*.")

    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        <div class="diff-box fdd-box">
            <h4 style="color: #475569; margin-bottom:5px;">Traditional FDD Tools</h4>
            <p style="font-size: 0.9em; color: #64748b; font-style: italic;">(Maintenance Logic)</p>
            <hr style="border:0.5px solid #e2e8f0; margin: 15px 0;">
            <p><b>Focus:</b> Asset Health & Hardware Reliability</p>
            <p><b>Core Question:</b> "Is the equipment broken?"</p>
            <p><b>Triggers:</b> Sensor failure, motor vibrations, seized valves, communication loss.</p>
            <p><b>Outcome:</b> Fix the motor / Replace the sensor.</p>
            <div style="background: white; padding: 15px; border-radius: 8px; margin-top: auto; border: 1px solid #e2e8f0;">
                <p style="margin:0; font-size:0.9em; color:#475569;"><b>Example Alarm:</b> <br><code style="color: #ef4444;">"AHU-1 Static Pressure Low (Fan Belt Broken)"</code></p>
            </div>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        st.markdown("""
        <div class="diff-box el-box">
            <h4 style="color: #166534; margin-bottom:5px;">EnergyLens</h4>
            <p style="font-size: 0.9em; color: #166534; font-style: italic;">(Operational Intent Logic)</p>
            <hr style="border:0.5px solid #bbf7d0; margin: 15px 0;">
            <p><b>Focus:</b> Strategic Justification of Consumption</p>
            <p><b>Core Question:</b> "Should it be running at all?"</p>
            <p><b>Triggers:</b> Intent mismatch, logic friction, schedule drift, occupancy mismatch.</p>
            <p><b>Outcome:</b> Update the strategy / Stop the waste.</p>
            <div style="background: white; padding: 15px; border-radius: 8px; margin-top: auto; border: 1px solid #bbf7d0;">
                <p style="margin:0; font-size:0.9em; color:#166534;"><b>Example Alert:</b> <br><code style="color: #10b981;">"AHU-1 Running at 100% Speed (Zone is Empty)"</code></p>
            </div>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("### The 'Gap' EnergyLens Fills")
    st.write("""
    **Buildings don't just waste energy when they fail — they waste energy even when everything is working perfectly.**
    
    FDD tells you when a machine stops working correctly. EnergyLens tells you when a perfectly healthy machine is consuming energy that the building **did not need to use**. We detect the invisible "grey zone" of wastage that exists between hardware health and comfort logic.
    """)
    st.info("💡 **Presentation Tip:** Use this tab if a committee member asks: 'Don't BMS systems already have fault detection built-in?'")

# =====================================================================
# EXPORT & FOOTER
# =====================================================================
st.divider()
with st.expander("📥 Export Evidence for Reporting"):
    export_df = df if 'df' in locals() else pd.DataFrame()
    st.dataframe(export_df, width='stretch')
    if not export_df.empty:
        st.download_button(
            "Download EnergyLens Audit CSV",
            export_df.to_csv().encode("utf-8"),
            file_name="energylens_audit_report.csv",
            mime="text/csv"
        )

st.markdown(
    f"<p style='text-align: center; color: #64748b; font-size: 12px; margin-top: 50px;'>"
    f"© 2026 <b>EnergyLens</b> Intelligence Layer · Standardized HVAC Waste Framework · Strategic Operational Intent <br>"
    f"Last Intelligence Sync: {time.strftime('%H:%M:%S')}"
    f"</p>", 
    unsafe_allow_html=True
)